<? php
echo '<html>';
echo '<head> </head>';
echo '';
echo '<style type='text/css'>';
echo '.embeddedServiceHelpButton .helpButton .uiButton {';
echo 'background-color: #338DD1;';
echo 'font-family: "Salesforce Sans", sans-serif;';
echo '}';
echo '.embeddedServiceHelpButton .helpButton .uiButton:focus {';
echo 'outline: 1px solid #338DD1;';
echo '}';
echo '@font-face {';
echo 'font-family: 'Salesforce Sans';';
echo 'src: url('https://www.sfdcstatic.com/system/shared/common/assets/fonts/SalesforceSans/SalesforceSans-Regular.woff') format('woff'),';
echo 'url('https://www.sfdcstatic.com/system/shared/common/assets/fonts/SalesforceSans/SalesforceSans-Regular.ttf') format('truetype');';
echo '}';
echo '</style>';
echo '';
echo '<script type='text/javascript' src='https://service.force.com/embeddedservice/5.0/esw.min.js'></script>';
echo '<script type='text/javascript'>';
echo 'var initESW = function(gslbBaseURL) {';
echo 'embedded_svc.settings.displayHelpButton = true; //Or false';
echo 'embedded_svc.settings.language = ''; //For example, enter 'en' or 'en-US'';
echo '';
echo '//embedded_svc.settings.defaultMinimizedText = '...'; //(Defaults to Chat with an Expert)';
echo '//embedded_svc.settings.disabledMinimizedText = '...'; //(Defaults to Agent Offline)';
echo '';
echo '//embedded_svc.settings.loadingText = ''; //(Defaults to Loading)';
echo '//embedded_svc.settings.storageDomain = 'yourdomain.com'; //(Sets the domain for your deployment so that visitors can navigate subdomains during a chat session)';
echo '';
echo '// Settings for Live Agent';
echo '//embedded_svc.settings.directToButtonRouting = function(prechatFormData) {';
echo '// Dynamically changes the button ID based on what the visitor enters in the pre-chat form.';
echo '// Returns a valid button ID.';
echo '//};';
echo '//embedded_svc.settings.prepopulatedPrechatFields = {}; //Sets the auto-population of pre-chat form fields';
echo '//embedded_svc.settings.fallbackRouting = []; //An array of button IDs, user IDs, or userId_buttonId';
echo '//embedded_svc.settings.offlineSupportMinimizedText = '...'; //(Defaults to Contact Us)';
echo '';
echo 'embedded_svc.settings.enabledFeatures = ['LiveAgent'];';
echo 'embedded_svc.settings.entryFeature = 'LiveAgent';';
echo '';
echo 'embedded_svc.init(';
echo ''https://alexanian-demo.my.salesforce.com',';
echo ''https://sdodemo-main-166ce2cf6b6-16a1239fbed.force.com/professional',';
echo 'gslbBaseURL,';
echo ''00D2E000000nU7D',';
echo ''Frank_Guru_2',';
echo '{';
echo 'baseLiveAgentContentURL: 'https://c.la1-c2-ia2.salesforceliveagent.com/content',';
echo 'deploymentId: '5722E000000Xk4A',';
echo 'buttonId: '5732E000000XkCz',';
echo 'baseLiveAgentURL: 'https://d.la1-c2-ia2.salesforceliveagent.com/chat',';
echo 'eswLiveAgentDevName: 'EmbeddedServiceLiveAgent_Parent04I2E000000XaQkUAK_16a236ec9fd',';
echo 'isOfflineSupportEnabled: false';
echo '}';
echo ');';
echo '};';
echo '';
echo 'if (!window.embedded_svc) {';
echo 'var s = document.createElement('script');';
echo 's.setAttribute('src', 'https://alexanian-demo.my.salesforce.com/embeddedservice/5.0/esw.min.js');';
echo 's.onload = function() {';
echo 'initESW(null);';
echo '};';
echo 'document.body.appendChild(s);';
echo '} else {';
echo 'initESW('https://service.force.com');';
echo '}';
echo '</script>';
echo '';
echo '</body>';
echo '</html>';
echo '';
?>